In [1]:
import pandas as pd
import numpy as np

In [2]:
melb_data=pd.read_csv("melb_data.csv")

In [3]:
melb_data_final = melb_data.iloc[:,[12,13,14,15]]

In [4]:
melb_data_final.head()

   Car  Landsize  BuildingArea  YearBuilt
0  1.0     202.0           NaN        NaN
1  0.0     156.0          79.0     1900.0
2  0.0     134.0         150.0     1900.0
3  1.0      94.0           NaN        NaN
4  2.0     120.0         142.0     2014.0

In [5]:
melb_data_final.Car.fillna(1.0 , inplace = True)
melb_data_final.YearBuilt.fillna(2000 , inplace = True)
melb_data_final.BuildingArea.fillna(80 , inplace = True)

C:\Users\Sayali\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [6]:
melb_data_final

       Car  Landsize  BuildingArea  YearBuilt
0      1.0     202.0          80.0     2000.0
1      0.0     156.0          79.0     1900.0
2      0.0     134.0         150.0     1900.0
3      1.0      94.0          80.0     2000.0
4      2.0     120.0         142.0     2014.0
5      0.0     181.0          80.0     2000.0
6      0.0     245.0         210.0     1910.0
7      2.0     256.0         107.0     1890.0
8      1.0       0.0          80.0     2000.0
9      2.0     220.0          75.0     1900.0
10     1.0       0.0          80.0     2000.0
11     2.0     214.0         190.0     2005.0
12     1.0       0.0          94.0     2009.0
13     1.0     195.0          80.0     2000.0
14     1.0       0.0          80.0     2000.0
15     2.0     238.0          97.0     1890.0
16     1.0     113.0         110.0     1880.0
17     1.0     138.0         105.0     1890.0
18     0.0     183.0          80.0     2000.0
19     1.0     150.0          73.0     1985.0
20     2.0     780.0         135.0     1900.0
21     2.0       0.0          80.0     2010.0
22     2.0    4290.0          27.0     2000.0
23     1.0       0.0          60.0     1970.0
24     1.0     124.0         135.0     2013.0
25     0.0     147.0          85.0     1900.0
26     1.0       0.0          80.0     2000.0
27     1.0     166.0         174.0     2012.0
28     1.0       0.0          50.0     2000.0
29     2.0      98.0         128.0     1920.0
...    ...       ...           ...        ...
13550  1.0     589.0          80.0     2000.0
13551  2.0     534.0          80.0     1970.0
13552  1.0     616.0          80.0     2000.0
13553  2.0    1005.0          80.0     1920.0
13554  2.0     438.0         151.0     1906.0
13555  3.0     832.0          80.0     2000.0
13556  1.0     466.0         103.0     2003.0
13557  2.0     689.0          80.0     2012.0
13558  2.0     741.0          80.0     2000.0
13559  1.0     723.0          80.0     2000.0
13560  2.0     717.0         310.0     1963.0
13561  2.0     948.0          80.0     2000.0
13562  1.0     312.0          80.0     2000.0
13563  2.0     470.0         151.0     1950.0
13564  1.0     607.0         102.0     1970.0
13565  2.0     791.0          80.0     2000.0
13566  2.0     986.0          80.0     2000.0
13567  3.0     696.0          80.0     2000.0
13568  2.0     704.0         200.0     1981.0
13569  2.0     551.0          80.0     2000.0
13570  2.0     674.0          80.0     2000.0
13571  2.0     717.0         191.0     1980.0
13572  1.0     210.0          79.0     2006.0
13573  1.0     662.0         172.0     1980.0
13574  2.0     256.0          80.0     2000.0
13575  2.0     652.0          80.0     1981.0
13576  2.0     333.0         133.0     1995.0
13577  4.0     436.0          80.0     1997.0
13578  5.0     866.0         157.0     1920.0
13579  1.0     362.0         112.0     1920.0

[13580 rows x 4 columns]